<?php
// 問題データ定義
$problems = array(
	array( "prefecture" => "岩手県",		"capital" => "盛岡" ),
	array( "prefecture" => "茨城県",		"capital" => "水戸" ),
	array( "prefecture" => "栃木県",		"capital" => "宇都宮" ),
	array( "prefecture" => "群馬県",		"capital" => "前橋" ),
	array( "prefecture" => "山梨県",		"capital" => "甲府" ),
	array( "prefecture" => "三重県",		"capital" => "津" ),
	array( "prefecture" => "滋賀県",		"capital" => "大津" ),
	array( "prefecture" => "島根県",		"capital" => "松江" ),
	array( "prefecture" => "香川県",		"capital" => "高松" ),
	array( "prefecture" => "愛媛県",		"capital" => "松山" ),
);
?>